version: '3'
services:
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    networks:
      - mediawiki_network
    command: >-
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email jan.bures@live.com --agree-tos --no-eff-email
             -d wiki.spacewarp.org
    volumes:
      - ./certbot_data/etc/letsencrypt:/etc/letsencrypt
      - ./certbot_data/www:/var/www/certbot

  nginx:
    container_name: nginx
    image: nginx:1.25
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mediawiki
    networks:
      - mediawiki_network
    volumes:
      - ./nginx_data/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx_data/access.log:/var/log/nginx/access.log
      - ./nginx_data/error.log:/var/log/nginx/error.log
      - ./certbot_data/etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot_data/www:/var/www/certbot

  mediawiki:
    container_name: mediawiki
    image: mediawiki:1.40
    restart: always
    depends_on:
      - database
    networks:
      - mediawiki_network
    volumes:
      - ./mediawiki_data/extensions:/var/www/html/extensions
      - ./mediawiki_data/images:/var/www/html/images
      - ./mediawiki_data/skins:/var/www/html/skins
      - ./mediawiki_data/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./mediawiki_data/php.ini:/usr/local/etc/php/php.ini

  database:
    container_name: database
    image: mariadb:10.6
    restart: always
    networks:
      - mediawiki_network
    environment:
      MYSQL_DATABASE: bitnami_mediawiki
      MYSQL_USER: bn_mediawiki
      MYSQL_PASSWORD: REDACTED
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./database_data:/var/lib/mysql

networks:
  mediawiki_network:
    driver: bridge