<?php
# This file was automatically generated by the MediaWiki 1.39.3
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "KSP 2 Modding Wiki";
$wgMetaNamespace = "KSP2_Modding_Wiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

## The protocol and server name to use in fully-qualified URLs
$wgServer = 'https://wiki.spacewarp.org';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/images/swlogo.svg",
	'icon' => "$wgResourceBasePath/images/swlogo.svg",
];
$wgFavicon = "$wgResourceBasePath/images/swlogo-icon.ico";
$wgAppleTouchIcon = "$wgResourceBasePath/images/swlogo-apple.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = 'spacewarp.noreply@gmail.com';
$wgPasswordSender = 'spacewarp.noreply@gmail.com';

$wgSMTP = [
    'host'      => 'ssl://smtp.gmail.com', // could also be an IP address. Where the SMTP server is located. If using SSL or TLS, add the prefix "ssl://" or "tls://".
    'IDHost'    => 'wiki.spacewarp.org',  // Generally this will be the domain name of your website (aka mywiki.org)
    'localhost' => 'wiki.spacewarp.org', // Same as IDHost above; required by some mail servers
    'port'      => 465, // Port to use when connecting to the SMTP server
    'auth'      => true, // Should we use SMTP authentication (true or false)
    'username'  => 'spacewarp.noreply@gmail.com', // Username to use for SMTP authentication (if being used)
    'password'  => 'REDACTED' // Password to use for SMTP authentication (if being used)
];

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "database";
$wgDBname = "bitnami_mediawiki";
$wgDBuser = "bn_mediawiki";
$wgDBpassword = "REDACTED";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgMaxUploadSize = 20 * 1024 * 1024;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# This should always be customized to a secret, unique string in LocalSettings.php.
# Installer.php sets it to a 64-character random string generated by MWCryptRand::generateHex( 64 );
$wgSecretKey = "REDACTED";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "REDACTED";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "citizen";
$wgDefaultMobileSkin = "citizen";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'Citizen' );

# End of automatically generated settings.
# Add more configuration options below.
$wgArticlePath = "/wiki/$1";
$wgUsePathInfo = true;

# wfLoadExtension( 'CategoryExplorer' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Discord' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'YouTube' );

# Custom log file
# $wgDebugLogFile = "/bitnami/mediawiki/debug-{$wgDBname}.log";

# Only allow registered users to edit the wiki
$wgGroupPermissions['*']['edit'] = false;

# Webhook for KSP2 Modding Society Discord server integration
$wgDiscordWebhookURL = [ 'REDACTED' ];